### ISSUE TITLE
CSS 100% height table with angular datatable

### ISSUE THREAD

**Issue by egel** [Contactis/translations-manager#2]
This issue appear when enabling scrollbar + CSS flex (for example in programmer-view) using [angular-datatable](https://github.com/l-lin/angular-datatables)

```
scrollbarV: true
```

Sample example:
![localhost 3000-programmer-view - google chrome_013](https://cloud.githubusercontent.com/assets/3322106/10369437/8e512d0a-6dda-11e5-8976-efae3c3485f6.png)

**Comment by pexak** [comment]
we'v migrated to boostrap, we will use bootstrap tables
