### ISSUE TITLE
Missing strings after few page reloads in tr-edit-table directive

### ISSUE THREAD

**Issue by egel** [Contactis/translations-manager#42]
After several page reloading the tr-edit-table directive behave weird ;)

Sample screenshot:
![selection_008](https://cloud.githubusercontent.com/assets/3322106/11504543/2dfd2a12-9846-11e5-8b47-2a5c6efc9ea9.png)

**Comment by pexak** [comment]
fixed, loopback sqlite connector problem

**Comment by egel** [comment]
After migrating to MySQL, this task has been resolved with 32e5841d5dc9a9d0c7d211e39dec13f89d02ef22
